title: Note
author: yinpeng
description: ğŸš€ To Keep Learningã€Keep Thinkingã€Keep Focus
theme: jekyll-theme-hacker
github:
  # repository_url: https://github.com/peng-yin/note/issues
  is_project_page: false
plugins:
  - jemoji
