title: Note
author: yinpeng
description: ğŸš€ To Keep Learningã€Keep Thinkingã€Keep Focus
theme: jekyll-theme-hacker
favicon: ./favicon.ico
github:
  repository_url: https://github.com/peng-yin/note/issues
plugins:
  - jemoji
