# ç«™ç‚¹åŸºç¡€é…ç½®
title: CodeNinja's Lab
author: peng-yin
description: ğŸš€ æ¢ç´¢ç¼–ç¨‹çš„æ— é™å¯èƒ½ | Keep Learningã€Keep Thinkingã€Keep Focus
url: "https://peng-yin.github.io/note"
baseurl: "/note"
permalink: /:year/:month/:day/:title/

# ç¤¾äº¤é“¾æ¥
social_links:
  github: peng-yin
  twitter: # å¦‚æœæœ‰Twitterå¯ä»¥æ·»åŠ 
  linkedin: # å¦‚æœæœ‰LinkedInå¯ä»¥æ·»åŠ 

# ä¸»é¢˜é…ç½®
remote_theme: pages-themes/hacker@v0.2.0
theme: jekyll-theme-hacker

# é¢å¤–è®¾ç½®
show_downloads: false
google_analytics: # å¦‚éœ€åˆ†æå¯æ·»åŠ GA ID
future: true
timezone: Asia/Shanghai
encoding: UTF-8
markdown: kramdown

# é¡µé¢å±•ç¤ºé…ç½®
header_pages:
  - about.md
  - categories.md
  - tags.md

# æ’ä»¶
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-github-metadata

# GitHubç›¸å…³é…ç½®
github:
  repository_url: https://github.com/peng-yin/note/issues
  is_project_page: true
  owner_url: https://github.com/peng-yin
  owner_name: yinpeng

# è‡ªå®šä¹‰è®¾ç½®
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: yinpeng
      comments: true
      toc: true
      excerpt_separator: <!--more-->

# SEOä¼˜åŒ–
twitter:
  username: # å¦‚æœæœ‰Twitterå¯ä»¥æ·»åŠ 
  card: summary_large_image

# åšå®¢åŠŸèƒ½å¢å¼º
paginate: 10
paginate_path: "/page:num/" 